apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/umbertocicciaa
              icon: github.png
  services.yaml: |
    - Creator:
        - Portfolio:
            href: https://umbertocicciaa.github.io/
            description: My portfolio
            icon: user.png
        - Blog:
            href: https://umbertocicciaa.github.io/blog-umbertodomenico-ciccia/
            description: My blog
            icon: blog.png

    - Social:
        - X:
            href: https://x.com/umberto_ciccia
            description: My x profile
            icon: twitter.png
        - LinkedIn:
            href: https://www.linkedin.com/in/umberto-domenico-ciccia/
            description: My LinkedIn profile
            icon: linkedin.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
