apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/umbertocicciaa
              icon: github.png
        - Gitlab:
            - abbr: GL
              href: https://gitlab.com/umbertocicciaa
              icon: gitlab.png
        - Notion:
            - abbr: N
              href: https://www.notion.so
              icon: notion.png
    - University:
        - Campus:
            - abbr: U
              href: https://unical.esse3.cineca.it
              icon: university.png
        - Courses:
            - abbr: L
              href: https://www.unical.it/didattica/offerta-formativa/catalogo/
              icon: library.png
  services.yaml: |
    - Homelab:
        - Grafana:
            href: http://grafana.192.168.0.104.nip.io
            description: Grafana dashboard
            icon: grafana.png
        - Jenkins:
            href: http://192.168.0.104/jenkins
            description: Jenkins dashboard
            icon: jenkins.png
        - pgAdmin:
            href: http://pgadmin.192.168.0.104.nip.io
            description: pgAdmin dashboard
            icon: pgadmin.png
    - Creator:
        - Portfolio:
            href: https://umbertocicciaa.github.io/
            description: My portfolio
            icon: https://img.shields.io/badge/GitHub%20Pages-222222?style=for-the-badge&logo=github%20Pages&logoColor=white
        - Blog:
            href: https://umbertocicciaa.github.io/blog-umbertodomenico-ciccia/
            description: My blog
            icon: https://img.shields.io/badge/Blogger-FF5722?style=for-the-badge&logo=blogger&logoColor=white

    - Social:
        - X:
            href: https://x.com/umberto_ciccia
            description: My x profile
            icon: twitter.png
        - LinkedIn:
            href: https://www.linkedin.com/in/umberto-domenico-ciccia/
            description: My LinkedIn profile
            icon: linkedin.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
